const path = require('path')
require('dotenv').config()
const express = require('express')
const mongoose = require('mongoose')
const methodOverride = require('method-override')
const morgan = require('morgan')
const carsRout = require('./routes/cars')
const { index } = require('./Controllers/cars')
const app = express()
const PORT = process.env.PORT
mongoose.connect(process.env.MONGODB_URI)
mongoose.connection.on(`connected`, () => {
  console.log(`connected to MongoDB ${mongoose.connection.name}.`)
})
app.use(express.urlencoded({ extended: false }))
app.use(methodOverride('_method'))
app.use(morgan(`dev`))
app.use(express.static(path.join(__dirname, 'public')))
app.get('/', async (req, res) => {
  res.render('index.ejs')
})
app.use(carsRout)
app.listen(PORT, () => {
  console.log(`listening on port ${PORT}`)
})
